import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <main className="flex h-screen items-center justify-center bg-sky-100 ">
          <div className="max-w-screen-lg h-full max-h-96 m-auto flex-1 px-4">
            <div className="w-full h-full placeholder:rounded-3xl bg-white shadow-lg p-8 ">
              {children}
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
